#cloud-config

ssh_authorized_keys:
  - ${authorized_key}

runcmd:
  - apt-get update
  - curl -fsSL https://get.docker.com/ | sh
  - curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
  - systemctl enable docker-tls-tcp.socket

write_files:
- path: /etc/systemd/system/docker.service.d/10-dune.conf
  content: |
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H fd:// --icc=false --userns-remap=default
- path: /etc/systemd/system/docker-tls-tcp.socket
  content: |
    [Unit]
    Description=Docker Secured Socket for the API

    [Socket]
    ListenStream=2376
    BindIPv6Only=both
    Service=docker.service

    [Install]
    WantedBy=sockets.target

power_state:
  mode: reboot
  condition: true
