#cloud-config

# hostname:
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD6slH962ReytD38MDj5knFHZdlecoxgYkPD+W/Jd1hIjxNry4KtjeTIfyPXXfOMpwHKI8a6xVpn3GMHqvXLe5eFUejUCpmmVotlZV/nvQyE6FvxsUX8uRIQq8FqbZ+YECc9lNRq44VqCxhYO6pkaGZHeZUGUcMo/8bVy/hg6uP7DtFTH8pqIPWzzfs1iGZLGY/gvVll4mTUZ8a3v8LHdQTKVhpDWF18hdhyAKNZUBlAqFPnA9tHhT84qvm9Av5l6DRkKfMwR3d/1aWXkNiFgb+YKQZ2z4Go7JvKhQmsA5SQAFRSI3YipShHOQzp+TtAKysjW1PLJ5/1gO+t0w+ZsUF matt@lanciv.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCJwHcu4WUeVRs7MRIxRFer/pDQjABR1SyV8fIJW6UUZqkXVdy7YdDXDslZMgam2esWWxlZVmhLwxRHd11aeNHvMdT8EB0bqFLLv9QJ3etHkz0FfRLUFCN0W42v1iKFkN6dqbxb8ZLGQTsh+10HYoAOpMYZnUUVo9DZKfqjezgGWbWJKqeB2UFv8N8rDun02nk8QImxtXAKoRiRn3UP7gagqUz0d/064t2Rg1vbFWaxRTvkoPOzpiHeAl+Wla2oRhjxu8mQN6fZSY8YS0aYafRo0H3wyspdhtPJNPXGxrcJczLPJwqfLdZf8FECRWca8cYH8IuPOUtHwXF3AMURTmKN jeff

runcmd:
  - apt-get update
  - curl -fsSL https://get.docker.com/ | sh
  - curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
  - systemctl enable docker-tls-tcp.socket

write_files:
- path: /etc/systemd/system/docker.service.d/10-dune.conf
  content: |
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H fd:// --icc=false --userns-remap=default
- path: /etc/systemd/system/docker-tls-tcp.socket
  content: |
    [Unit]
    Description=Docker Secured Socket for the API

    [Socket]
    ListenStream=2376
    BindIPv6Only=both
    Service=docker.service

    [Install]
    WantedBy=sockets.target

power_state:
  mode: reboot
  condition: true
