#cloud-config

ssh_authorized_keys:
  - ${authorized_key}

runcmd:
  - apt-get update
  - curl -fsSL https://get.docker.com/ | sh
  - curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
  - systemctl enable docker-tls-tcp.socket
  - systemctl enable dd-agent.service

write_files:
- path: /etc/systemd/system/docker.service.d/10-dune.conf
  content: |
    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -H fd:// --icc=false --userns-remap=default
- path: /etc/systemd/system/docker-tls-tcp.socket
  content: |
    [Unit]
    Description=Docker Secured Socket for the API

    [Socket]
    ListenStream=2376
    BindIPv6Only=both
    Service=docker.service

    [Install]
    WantedBy=sockets.target
- path: /etc/systemd/system/dd-agent.service
  content: |
    [Unit]
    Description=Datadog Agent
    Requires=docker.service
    After=docker.service

    [Service]
    Restart=always
    EnvironmentFile=/etc/os-release
    ExecStartPre=-/usr/bin/docker stop dd-agent
    ExecStartPre=-/usr/bin/docker rm -f dd-agent
    ExecStartPre=/usr/bin/docker pull datadog/docker-dd-agent
    TimeoutStartSec=0
    ExecStartPre=-/usr/bin/docker kill dd-agent
    ExecStartPre=-/usr/bin/docker rm dd-agent
    ExecStart=/usr/bin/docker run --name dd-agent \
        -h %H \
        --privileged \
        --userns=host \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /proc/mounts:/host/proc/mounts:ro \
        -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
        -e API_KEY=${datadog_key} \
        datadog/docker-dd-agent
    ExecStop=/usr/bin/docker stop dd-agent

power_state:
  mode: reboot
  condition: true
