version: 2
executorType: docker
containerInfo:
  - image: alpine:edge
    cmd: ["/bin/sh"]
stages:
  build:
    environment:
      - AWS_DEFAULT_REGION: "us-east-1"
    workDir: /src
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        name: Setup
        command: |
          apk add -U bash terraform make ca-certificates git go openssh wget unzip
          wget https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
          unzip terraform_0.8.8_linux_amd64.zip
          mv terraform /usr/local/bin
          rm terraform_0.8.8_linux_amd64.zip
      - type: checkout
      - type: shell
        name: Terraform
        command: |
          set -euo pipefail
          export AWS_ACCESS_KEY_ID="$TF_VAR_access_key"
          export AWS_SECRET_ACCESS_KEY="$TF_VAR_secret_key"
          make plan
          #if [[ "$CIRCLE_BRANCH" = "master" ]]; then
          #  make apply
          #fi
