#!/bin/sh
set -eo pipefail

SERVICE_ACCOUNT=${1?}
kubectl create serviceaccount $SERVICE_ACCOUNT || true

SECRET_NAME="$(kubectl get serviceaccount $SERVICE_ACCOUNT -ogo-template='{{index .secrets 0 "name"}}')"

NAME="$(kubectl config view --minify -ogo-template='{{index .clusters 0 "name"}}')"
SERVER="$(kubectl config view --minify -ogo-template='{{index .clusters 0 "cluster" "server"}}')"
TOKEN="$(kubectl get secret $SECRET_NAME -ogo-template='{{.data.token}}' | base64 -D)"

template="apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{index .data \"ca.crt\"}}
    server: $SERVER
  name: $NAME
contexts:
- context:
    cluster: $NAME
    user: $SERVICE_ACCOUNT
  name: $NAME
current-context: $NAME
kind: Config
users:
- name: $SERVICE_ACCOUNT
  user:
    token: $TOKEN
"

kubectl get secret $SECRET_NAME -ogo-template="$template"
